name: Deploy Azure Function

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./infrastructure/function-app.bicep
          parameters: ./infrastructure/function-app.parameters.json

  publish-function:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    env:
      AZURE_FUNCTIONAPP_NAME: ${{ needs.deploy-infrastructure.outputs.functionAppName }}
      AZURE_FUNCTIONAPP_PACKAGE_PATH: "./src/TodoApi/"
      DOTNET_VERSION: "6.0.302"
      PROJECT_PATH: "./src/"
    steps:
      - uses: actions/checkout@main

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Build Azure Functions App"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: "Deploy Azure Functions App"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
